/**
 * legacySettings.js — the `settings` blocks the archived systems read.
 *
 * Nothing imports this. It exists so that restoring an archived ability is a
 * copy-paste rather than an archaeology exercise: every number here is the value
 * the effect was actually tuned at when it was retired.
 *
 * To restore one, spread its block into `src/config/settings.js` and add its id
 * to `ELEMENTS` / `ELEMENT_META`. See ../README.md.
 */

/** The freehand path preview drawn under the cursor (effects/PathTrail.js). */
export const trail = {
  width: 0.55,
  length: 1.0, // 0..1 fraction of the drawn path that stays visible
  opacity: 0.85,
  glow: 1.4,
  colorInner: '#eafcff',
  colorOuter: '#4fb9ff',
  flowSpeed: 1.6,
  noiseStrength: 0.55,
  noiseFrequency: 2.6,
  dissolveSpeed: 1.5,
  taper: 0.65,
  softness: 0.65,
  height: 0.07,
  sparkle: 0.6
};

/** Freehand stroke filtering + resampling (input/PathDrawer.js). */
export const input = {
  minPointDistance: 0.22,
  minPathLength: 1.6,
  maxPoints: 220,
  smoothing: 0.35,
  curveTension: 0.5,
  samplesPerUnit: 3.0
};

/** Walk mode — the leap, the air scooter and the ride (animation/WalkController.js). */
export const walk = {
  jumpSpeed: 7.0,
  jumpHeight: 1.75,
  jumpMin: 0.45,
  jumpMax: 1.15,
  tuck: 0.62,
  poseBlend: 0.45,

  speed: 5.0,
  accel: 0.45,
  brake: 0.6,
  dismountTime: 0.55,
  returnHome: false,

  hover: 0.06,
  seatSink: 0.34,
  bob: 0.035,
  bobRate: 2.3,
  lean: 26,
  leanRate: 2.0,
  leanDamping: 0.004,
  turnDamping: 0.0001,

  radius: 0.46,
  squash: 0.11,
  spin: 1.6,
  bands: 7.0,
  twist: 2.4,
  filamentSharp: 0.62,
  turbulence: 0.5,
  haze: 0.5,
  wobble: 0.08,
  fresnel: 1.5,
  opacity: 1.0,
  glow: 1.35,
  colorInner: '#f2fdff',
  colorOuter: '#5cc8ee',

  dustRate: 240,
  dustSize: 0.18,
  dustLifetime: 0.85,
  lightIntensity: 6,
  lightRadius: 7,
  lightColor: '#bfe8ff',
  landShake: 0.35
};

/** FIRE — raymarched black-body flame volume. */
export const fire = {
  speed: 11.5,
  lifetime: 2.6,
  flightHeight: 1.0,
  flightArc: 0.29,
  flameWidth: 0.22,
  headSize: 1.89,
  flameHeight: 1.84,
  wakeSpread: 0.19,
  bulge: 0.18,
  bulgeScale: 0.34,
  vortex: 0.16,
  ringFrequency: 0.0,
  ringSpeed: 4.7,
  flameCurl: 0.45,
  flameTurbulence: 3.2,
  flameWarp: 0.2,
  tongueStretch: 1.38,
  streamStretch: 1.31,
  lick: 3.1,
  wisps: 0.81,
  shred: 1.57,
  detailOctaves: 5,
  flameSpeed: 4.06,
  buoyancy: 3.09,
  detachment: 0.9,
  wakeRise: 0,
  volumeDensity: 2.09,
  soot: 1.42,
  coreClarity: 0.54,
  volumeSteps: 35,
  streamLength: 10.0,
  flicker: 0.96,
  glow: 3.06,
  opacity: 0.96,
  fresnel: 1.1,
  noiseStrength: 1.55,
  noiseFrequency: 4.16,
  noiseSpeed: 1.5,
  softness: 0.42,
  tempCore: 1980,
  tempEdge: 1590,
  emissionCurve: 4.5,
  heatFocus: 0.57,
  heatFalloff: 1.86,
  heatFollow: 0.23,
  tailHeat: 0.28,
  paletteBlend: 0.0,
  scatter: 1.61,
  scatterFalloff: 3.4,
  colorCore: '#fff6d8',
  colorMid: '#ffb02e',
  colorEdge: '#ff3d10',
  colorSmoke: '#181616',
  emberCount: 1.24,
  emberRate: 210,
  emberSize: 0.075,
  emberSpeed: 4.55,
  emberLifetime: 2.75,
  smokeDensity: 1.05,
  smokeSpeed: 1.28,
  smokeSize: 0.76,
  smokeLifetime: 4.75,
  sparkRate: 200,
  sparkSpeed: 7.0,
  heatDistortion: 0.0,
  distortionRadius: 1.6,
  lightIntensity: 13,
  lightRadius: 12,
  lightColor: '#ff7a26',
  explosionSize: 3.0,
  explosionBrightness: 2.2,
  explosionShake: 1.0,
  explosionFlash: 0.55
};

/** WATER — raymarched surface, spray and a splash crown. */
export const water = {
  speed: 7.5,
  lifetime: 3.0,
  height: 1.0,
  surge: 0.2,
  surgeLength: 1.82,
  surgeSpeed: 4.17,
  wakeSag: 0.35,
  radius: 0.1,
  headSize: 1.9,
  crest: 1.5,
  streamLength: 12.0,
  waveAmplitude: 0.26,
  waveFrequency: 1.8,
  chop: 0.6,
  flowSpeed: 1.9,
  noiseFrequency: 3.2,
  swirl: 0.9,
  detail: 0.35,
  streamStretch: 3.4,
  crestSharpness: 0.1,
  volumeSteps: 32,
  transparency: 0.68,
  depthDensity: 0.2,
  fresnel: 2.65,
  envIntensity: 1.0,
  skyReflection: 3.0,
  specular: 1.6,
  translucency: 2.5,
  foam: 2.5,
  foamSharpness: 2.5,
  shred: 0.8,
  shredDepth: 0.02,
  refraction: 0.1,
  glow: 0.8,
  opacity: 1.0,
  colorDeep: '#052a45',
  colorShallow: '#2ec4d6',
  colorFoam: '#eaf9ff',
  dropletRate: 320,
  dropletSize: 0.075,
  dropletSpeed: 3.1,
  dropletLifetime: 1.5,
  sprayRate: 190,
  spraySpeed: 5.4,
  foamRate: 75,
  foamSize: 0.16,
  foamLifetime: 1.3,
  mistDensity: 0.2,
  mistSize: 0.9,
  mistLifetime: 1.8,
  wakeRate: 2,
  lightIntensity: 14,
  lightRadius: 10,
  lightColor: '#3aa8ff',
  splashSize: 2.2,
  splashIntensity: 0.6,
  crownJets: 18,
  rippleSize: 6.0,
  rippleSpeed: 1.0,
  foamSpread: 5.0,
  foamLingering: 3.4,
  explosionShake: 0.6,
  explosionFlash: 0.12
};

/** EARTH — instanced crust, heaved boulders, finale tower. */
export const earth = {
  speed: 6.0,
  lifetime: 3.2,
  crustWidth: 0.5,
  crustDensity: 1.12,
  plateSize: 1.38,
  plateThickness: 0.49,
  paintTime: 0.03,
  crackDelay: 0.84,
  crackSharpness: 0.61,
  plateTilt: 0.97,
  plateLift: 0.44,
  plateSpread: 0.19,
  rockCount: 1.15,
  rockSpacing: 1.74,
  rockSize: 0.45,
  rockRandomness: 0.74,
  riseHeight: 1.68,
  riseSpeed: 4.95,
  sinkDelay: 0.48,
  tumble: 1.0,
  colorRock: '#6b5744',
  colorRockDark: '#3a2e24',
  colorMoss: '#4f6b33',
  crackWidth: 0.78,
  crackDepth: 0.85,
  groundDisplacement: 0.31,
  dustAmount: 0.49,
  dustLifetime: 1.3,
  dustSize: 1.58,
  debrisRate: 111,
  debrisVelocity: 9,
  debrisSize: 0.03,
  debrisLifetime: 1.6,
  pebbleRate: 40,
  lightIntensity: 8,
  lightRadius: 7,
  lightColor: '#ffa855',
  glow: 1.38,
  towerHeight: 6.2,
  towerWidth: 0.73,
  towerRiseTime: 1.21,
  towerHold: 2.4,
  towerRocks: 16,
  towerRockRadius: 2.0,
  shakeIntensity: 1.5,
  shakeDuration: 1.38,
  explosionFlash: 0.15
};

/** WIND — combed silk sheets, vortex, tornado finale. */
export const wind = {
  speed: 14.0,
  lifetime: 2.4,
  ribbonCount: 3,
  ribbonWidth: 2.1,
  ribbonOpacity: 0.91,
  ribbonLength: 24.0,
  spiralRadius: 1.05,
  sheetTwist: 1.5,
  rotationSpeed: 5.5,
  vortexStrength: 1.6,
  swirlSpeed: 2.2,
  filamentCount: 28,
  filamentSharpness: 0.56,
  turbulence: 0.8,
  haze: 0.22,
  noiseStrength: 0.71,
  noiseFrequency: 0.9,
  distortion: 0.08,
  fresnel: 1.36,
  opacity: 0.6,
  glow: 0.95,
  colorInner: '#f4fcff',
  colorOuter: '#b6d8ea',
  leafCount: 52,
  leafSize: 0.07,
  leafSpin: 4.7,
  leafLifetime: 2.5,
  dustAmount: 2.14,
  dustSize: 0.06,
  dustRate: 190,
  lightIntensity: 6,
  lightRadius: 8,
  lightColor: '#bfe8ff',
  tornadoHeight: 8.3,
  tornadoRadius: 2.2,
  tornadoDuration: 1.6,
  tornadoNeck: 0.2,
  tornadoShells: 3,
  tornadoRoughness: 0.17,
  tornadoLean: 0.55,
  burstIntensity: 1.5,
  explosionShake: 0.42,
  explosionFlash: 0.2
};

/** HUD presentation for the retired elements. */
export const ELEMENT_META = {
  fire: { label: 'Fire', accent: '#ff6a1a', glyph: '🜂', hint: 'Firebending' },
  water: { label: 'Water', accent: '#31b6ff', glyph: '🜄', hint: 'Waterbending' },
  earth: { label: 'Earth', accent: '#b98a4d', glyph: '🜃', hint: 'Earthbending' },
  wind: { label: 'Air', accent: '#c9f0ff', glyph: '🜁', hint: 'Airbending' }
};

/** The two interaction modes the drawn stroke used to switch between. */
export const MODE_META = {
  casting: { label: 'Cast', glyph: '✦', hint: 'Casting mode', blurb: 'Draw a path. Release to cast.' },
  walk: { label: 'Walk', glyph: '◎', hint: 'Walk mode', blurb: 'Draw a path. Release to ride it.' }
};
